import { createSectionedPdf } from '../../api/_lib/pdf.js';

import type { RanchReport } from './ranchReport.js';
import { ranchReportSections } from './ranchReportExport.js';

/*
 * The ranch report as a PDF, rendered in the browser.
 *
 * Split from ranchReportExport.ts so it can be imported lazily: this module is
 * what pulls in pdf-lib, and most sessions never export anything.
 *
 * It goes through the same createSectionedPdf that renders bills of sale and
 * sale-packet covers, so the report a rancher hands to their banker is laid out
 * like every other document the product produces — and a layout fix lands in
 * both at once instead of in whichever one someone remembered.
 */
type ReportBranding = { logo: Uint8Array; mark: Uint8Array; watermark: Uint8Array };

async function loadReportBranding(): Promise<ReportBranding> {
  const load = async (path: string) => {
    const response = await fetch(path);
    if (!response.ok) throw new Error('Report branding could not be loaded. Please try again.');
    return new Uint8Array(await response.arrayBuffer());
  };
  const [logo, mark, watermark] = await Promise.all([
    load('/brand/xbar-report-horse.png'),
    load('/brand/xbar-report-mark.png'),
    load('/brand/xbar-report-watermark.png'),
  ]);
  return { logo, mark, watermark };
}

export async function renderReportPdf(
  report: RanchReport,
  ranchName: string,
  branding?: ReportBranding,
): Promise<Uint8Array> {
  // The report's own local calendar date. See ranchReport.ts: the UTC slice
  // printed tomorrow's date on a US evening, beside monthly totals keyed to
  // today — on the page that goes to a banker.
  const generatedOn = report.generatedOn;
  return createSectionedPdf({
    title: 'Ranch Report',
    letterhead: ranchName || 'XBAR Ranch Ledger',
    continuationHeaders: true,
    branding: branding ?? (await loadReportBranding()),
    reference: `Generated ${generatedOn} · ${report.horseCount} horses`,
    sections: ranchReportSections(report),
    footer: 'Generated by XBAR™ · Based on workspace records',
  });
}
