import { createSectionedPdf } from '../../api/_lib/pdf.js';

import type { RanchReport } from './ranchReport.js';
import { ranchReportSections } from './ranchReportExport.js';

/*
 * The ranch report as a PDF, rendered in the browser.
 *
 * Split from ranchReportExport.ts so it can be imported lazily: this module is
 * what pulls in pdf-lib, and most sessions never export anything.
 *
 * It goes through the same createSectionedPdf that renders bills of sale and
 * sale-packet covers, so the report a rancher hands to their banker is laid out
 * like every other document the product produces — and a layout fix lands in
 * both at once instead of in whichever one someone remembered.
 */
export async function renderReportPdf(report: RanchReport, ranchName: string): Promise<Uint8Array> {
  const generatedOn = report.generatedAt.slice(0, 10);
  return createSectionedPdf({
    title: 'Ranch Report',
    letterhead: ranchName || 'XBAR Ranch Ledger',
    reference: `Generated ${generatedOn} · ${report.horseCount} horses`,
    sections: ranchReportSections(report),
    footer: 'Generated by XBAR Ranch Ledger',
  });
}
