import { useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useCloudStore } from '@/store/useCloudStore';
import './authExperience.css';

const features = ['Horse records', 'Health & compliance', 'Document vault', 'Ownership & title', 'Sale packets', 'Budget ledger'];
const plans = [{ name: 'Starter', price: '$29', fit: 'Independent owners' }, { name: 'Professional', price: '$79', fit: 'Growing programs' }, { name: 'Ranch Ops', price: '$199', fit: 'Working ranch teams' }, { name: 'Enterprise', price: '$499', fit: 'Multi-operation groups' }];
const signupPath = (plan?: string) => `/login?mode=signup${plan ? `&plan=${encodeURIComponent(plan)}` : ''}`;
function Wordmark() { return <span className="xbar-wordmark"><span className="xbar-wordmark__mark">XB</span><span className="xbar-wordmark__copy"><strong>XBAR</strong><span>Ranch platform</span></span></span>; }

export default function Landing() {
  const navigate = useNavigate(); const session = useCloudStore((state) => state.session);
  useEffect(() => { if (session) navigate('/', { replace: true }); }, [session, navigate]);
  return <main className="lp-shell" style={{ display: 'block', minHeight: '100vh' }}>
    <nav style={{ position: 'sticky', top: 0, zIndex: 20, display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px clamp(16px,4vw,52px)', borderBottom: '1px solid rgba(255,255,255,.07)', background: 'rgba(2,4,8,.88)', backdropFilter: 'blur(18px)' }}><Link to="/landing" aria-label="XBAR home"><Wordmark /></Link><div style={{ display: 'flex', gap: 8 }}><Link className="public-action public-action--quiet" to="/login">Sign in</Link><Link className="public-action public-action--primary" to={signupPath('Ranch Ops')}>Start free</Link></div></nav>
    <section style={{ minHeight: '72vh', display: 'grid', placeItems: 'center', padding: '72px 20px', textAlign: 'center', background: 'radial-gradient(circle at 50% 20%,rgba(25,94,205,.25),transparent 38%)' }}><div style={{ maxWidth: 820 }}><p className="lp-card-label">The operating system for modern horse operations</p><h1 style={{ margin: '12px auto 20px', maxWidth: '12ch', color: '#edf6ff', fontSize: 'clamp(3rem,8vw,6.6rem)', lineHeight: .94, letterSpacing: '-.075em' }}>Run a tighter horse operation.</h1><p style={{ margin: '0 auto 32px', maxWidth: 650, color: 'rgba(176,204,235,.7)', fontSize: 'clamp(16px,2vw,20px)', lineHeight: 1.65 }}>Keep every horse, record, obligation, document, and sale-ready detail in one trusted command center.</p><div style={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: 12 }}><Link className="public-action public-action--primary" to={signupPath('Ranch Ops')}>Start your 14-day trial</Link><Link className="public-action" to="/login">Open your workspace</Link></div></div></section>
    <section style={{ padding: '64px clamp(20px,6vw,84px)', borderTop: '1px solid rgba(255,255,255,.06)' }}><div style={{ maxWidth: 1120, margin: 'auto' }}><p className="lp-card-label">One source of truth</p><h2 style={{ color: '#edf6ff', fontSize: 'clamp(2rem,4vw,3.4rem)', letterSpacing: '-.055em', maxWidth: 620 }}>Proof ready when the work, buyer, vet, or auditor asks.</h2><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(190px,1fr))', gap: 14, marginTop: 32 }}>{features.map((feature) => <div className="lp-feature" key={feature} style={{ minHeight: 92, justifyContent: 'center' }}>{feature}</div>)}</div></div></section>
    <section style={{ padding: '64px clamp(20px,6vw,84px)', borderTop: '1px solid rgba(255,255,255,.06)' }}><div style={{ maxWidth: 1120, margin: 'auto' }}><p className="lp-card-label">Plans that grow with the operation</p><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(220px,1fr))', gap: 14, marginTop: 28 }}>{plans.map((plan) => <article key={plan.name} style={{ padding: 24, border: plan.name === 'Ranch Ops' ? '1px solid rgba(99,168,255,.5)' : '1px solid rgba(255,255,255,.09)', borderRadius: 14, background: plan.name === 'Ranch Ops' ? 'rgba(28,105,232,.12)' : 'rgba(255,255,255,.025)' }}><p className="lp-card-label">{plan.name}</p><strong style={{ display: 'block', margin: '8px 0', color: '#edf6ff', fontSize: 34 }}>{plan.price}<small style={{ fontSize: 13, color: 'rgba(176,204,235,.55)' }}>/mo</small></strong><p className="lp-card-sub">{plan.fit}</p><Link className="public-action" style={{ width: '100%', marginTop: 18 }} to={signupPath(plan.name)}>Choose {plan.name}</Link></article>)}</div></div></section>
    <footer style={{ padding: 32, textAlign: 'center', color: 'rgba(150,180,215,.48)', borderTop: '1px solid rgba(255,255,255,.06)' }}>XBAR Ranch Platform</footer>
  </main>;
}
