import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { isSupabaseConfigured } from '@/lib/platformConfig';
import { useCloudStore } from '@/store/useCloudStore';
import { useUiStore } from '@/store/useUiStore';
import { useXbarStore } from '@/store/useXbarStore';
import './authExperience.css';

type AuthMode = 'signin' | 'signup'; type BusyState = 'password' | 'google' | 'facebook' | 'apple' | 'reset' | '';
const features = ['Horse records', 'Health & compliance', 'Documents', 'Expenses', 'Ownership'];

export default function Login() {
  const navigate = useNavigate(); const location = useLocation(); const [params, setParams] = useSearchParams();
  const pushToast = useUiStore((s) => s.pushToast); const cloud = useCloudStore(); const initializeWorkspace = useXbarStore((s) => s.initializeWorkspace);
  const [email, setEmail] = useState(() => localStorage.getItem('xbar-remembered-email') ?? ''); const [password, setPassword] = useState(''); const [remember, setRemember] = useState(() => localStorage.getItem('xbar-remember-me') === 'true'); const [showPassword, setShowPassword] = useState(false); const [busy, setBusy] = useState<BusyState>('');
  const authMode: AuthMode = params.get('mode') === 'signup' ? 'signup' : 'signin'; const selectedPlan = params.get('plan') ?? ''; const redirectTarget = useMemo(() => (location.state as { from?: string } | null)?.from || (selectedPlan ? `/subscriptions?plan=${encodeURIComponent(selectedPlan)}` : '/'), [location.state, selectedPlan]); const supabaseReady = isSupabaseConfigured();
  const setMode = (mode: AuthMode) => { const next = new URLSearchParams(); if (mode === 'signup') next.set('mode', 'signup'); if (selectedPlan) next.set('plan', selectedPlan); setParams(next, { replace: true }); };
  useEffect(() => { if (cloud.session && cloud.status === 'signed-in') navigate(redirectTarget, { replace: true }); }, [cloud.session, cloud.status, navigate, redirectTarget]);
  const toast = (title: string, result: { ok: boolean; message: string }) => pushToast({ title, message: result.message, tone: result.ok ? 'success' : 'error' });
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy('password'); const result = authMode === 'signin' ? await cloud.signInWithPassword(email, password) : await cloud.signUpWithPassword(email, password); if (remember) { localStorage.setItem('xbar-remember-me', 'true'); localStorage.setItem('xbar-remembered-email', email); } else { localStorage.removeItem('xbar-remember-me'); localStorage.removeItem('xbar-remembered-email'); } toast(result.ok ? (authMode === 'signin' ? 'Welcome back' : 'Account created') : 'We could not complete that', result); setBusy(''); };
  const oauth = async (provider: 'google' | 'facebook' | 'apple') => { setBusy(provider); const result = provider === 'google' ? await cloud.signInWithGoogle() : provider === 'facebook' ? await cloud.signInWithFacebook() : await cloud.signInWithApple(); toast(result.ok ? `Continue with ${provider}` : `${provider} sign-in unavailable`, result); setBusy(''); };
  const reset = async () => { setBusy('reset'); const result = await cloud.sendPasswordReset(email); toast(result.ok ? 'Reset email sent' : 'Reset unavailable', result); setBusy(''); };
  const enterWorkspace = () => { localStorage.setItem('xbar-command-center-entry', 'true'); initializeWorkspace({ businessName: 'XBAR Ranch', ranchName: 'XBAR Ranch' }); navigate(redirectTarget, { replace: true }); };
  return <main className="xbar-login-shell lp-shell"><div className="xbar-login-noise" aria-hidden="true" /><div className="lp-frame"><section className="lp-brand" aria-labelledby="login-brand-title"><div className="brand-canvas" aria-hidden="true"><div className="brand-canvas__lockup"><span className="brand-canvas__x">XB</span><span className="brand-canvas__bar">XBAR</span><span className="brand-canvas__rule" /></div></div><div className="lp-tagline"><strong id="login-brand-title">Horse Management.</strong><span>Reimagined.</span></div><div className="lp-features">{features.map((feature) => <div className="lp-feature" key={feature}>{feature}</div>)}</div><p className="lp-card-sub">Built for ranches, breeders, and serious horse owners.</p></section>
  <section className="lp-auth" aria-label={authMode === 'signin' ? 'Sign in to XBAR' : 'Create an XBAR account'}><div className="lp-card"><p className="lp-card-label">{authMode === 'signin' ? 'Welcome back' : selectedPlan ? `${selectedPlan} trial` : 'Start your operation'}</p><h1 className="lp-card-title">{authMode === 'signin' ? 'Sign in to your account' : 'Create your XBAR account'}</h1><p className="lp-card-sub">{selectedPlan ? `Create your workspace, then review ${selectedPlan} in secure checkout.` : 'Your ranch, horses, records, and next actions in one place.'}</p>
  {supabaseReady ? <form className="lp-form" onSubmit={submit} aria-busy={busy !== ''}><label className="lp-label"><span className="lp-label-text">Email</span><input className="lp-input" type="email" value={email} onChange={(e) => setEmail(e.target.value)} autoComplete="email" required /></label><label className="lp-label"><span className="lp-label-text">Password</span><div className="lp-input-wrap"><input className="lp-input" type={showPassword ? 'text' : 'password'} value={password} onChange={(e) => setPassword(e.target.value)} autoComplete={authMode === 'signin' ? 'current-password' : 'new-password'} minLength={8} required /><button className="lp-pw-eye" type="button" onClick={() => setShowPassword((value) => !value)} aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? 'Hide' : 'Show'}</button></div></label><div className="lp-options"><label className="lp-remember"><input type="checkbox" checked={remember} onChange={(e) => setRemember(e.target.checked)} /> Remember me</label>{authMode === 'signin' && <button className="lp-forgot" type="button" disabled={!email || busy !== ''} onClick={reset}>{busy === 'reset' ? 'Sending...' : 'Forgot password?'}</button>}</div><button className="lp-btn-primary" type="submit" disabled={!email || password.length < 8 || busy !== ''}>{busy === 'password' ? 'Working...' : authMode === 'signin' ? 'Sign in' : 'Create account'}</button><div className="lp-divider"><span>or</span></div>{(['google','facebook','apple'] as const).map((provider) => <button key={provider} className="lp-btn-social" type="button" disabled={busy !== ''} onClick={() => oauth(provider)}>Continue with {provider[0].toUpperCase() + provider.slice(1)}</button>)}</form> : <div><p className="lp-card-sub">Cloud sign-in is not configured yet. You can still enter the workspace and evaluate the complete ranch command center.</p><button className="lp-btn-enter" type="button" onClick={enterWorkspace}>Enter workspace</button></div>}
  <div className="lp-mode-switch"><span>{authMode === 'signin' ? "Don't have an account?" : 'Already have an account?'}</span><button type="button" onClick={() => setMode(authMode === 'signin' ? 'signup' : 'signin')}>{authMode === 'signin' ? 'Create one' : 'Sign in'}</button></div><Link className="public-action public-action--quiet" to="/landing">Back to XBAR overview</Link></div></section></div></main>;
}
