import assert from 'node:assert/strict';
import test from 'node:test';
import {
  legalDocuments,
  legalDocumentById,
  legalDocumentToHtml,
  SUPPORT_CONTACT,
  getLegalDocument,
} from '../src/lib/legalDocuments.js';

const sectionTitles = (id: keyof typeof legalDocumentById) =>
  getLegalDocument(id).sections.map((section) => section.title);

test('SUPPORT_CONTACT carries the real support email; address still pending', () => {
  assert.equal(SUPPORT_CONTACT.email, 'Xbarje@gmail.com');
  assert.match(
    SUPPORT_CONTACT.address,
    /^\[.*\]$/,
    'address must stay a bracketed placeholder until Erin supplies one',
  );
});

test('every legal document carries a contact block using SUPPORT_CONTACT', () => {
  assert.equal(legalDocuments.length, 6);
  for (const legalDoc of legalDocuments) {
    const contact = legalDoc.sections.find((section) => section.title === 'Contact us');
    assert.ok(contact, `${legalDoc.id} is missing a Contact us section`);
    const body = contact.body.join(' ');
    assert.ok(body.includes(SUPPORT_CONTACT.email), `${legalDoc.id} contact block omits SUPPORT_CONTACT.email`);
    assert.ok(!body.includes('[COMPANY ADDRESS]'), `${legalDoc.id} prints the address placeholder to customers`);
  }
});

test('terms gains termination, assignment, entire agreement, and contact sections', () => {
  const titles = sectionTitles('terms');
  assert.ok(titles.includes('Term, suspension, and termination'));
  assert.ok(titles.includes('Assignment'));
  assert.ok(titles.includes('Entire agreement'));
  assert.ok(titles.includes('Contact us'));
});

test('privacy gains rights, cookies, children, and contact sections', () => {
  const titles = sectionTitles('privacy');
  assert.ok(titles.includes('Your choices and rights'));
  assert.ok(titles.includes('Cookies and similar technologies'));
  assert.ok(titles.includes("Children's privacy"));
  assert.ok(titles.includes('Contact us'));
});

test('billing renewal wording covers annual terms', () => {
  const renewal = getLegalDocument('subscription-billing').sections.find(
    (section) => section.title === 'Automatic renewal',
  );
  assert.ok(renewal);
  assert.ok(renewal.body.join(' ').includes('monthly or annual, as selected'));
  assert.ok(!renewal.body.join(' ').includes('monthly basis'));
});

test('privacy payment wording drops the "intentionally" hedge', () => {
  const body = getLegalDocument('privacy')
    .sections.flatMap((section) => section.body)
    .join(' ');
  assert.ok(!body.includes('does not intentionally store'));
  assert.ok(body.includes('XBAR does not store full payment card numbers in the application database'));
});

test('trademark notice uses the proper glyph and claims only real brand marks', () => {
  const marks = getLegalDocument('trademark-notice').sections.find((section) => section.title === 'XBAR marks');
  assert.ok(marks);
  const body = marks.body.join(' ');
  assert.ok(body.includes('™'), 'marks should use the proper ™ glyph');
  assert.ok(!body.includes('(TM)'), 'parenthetical (TM) must not appear');
  assert.ok(!body.includes('XBAR My Horses'), 'internal feature names must not be claimed as marks');
  assert.ok(!body.includes('claimed by'));
});

test('printable html carries no draft metadata or review notices', () => {
  for (const legalDoc of legalDocuments) {
    const html = legalDocumentToHtml(legalDoc);
    assert.ok(!html.includes('Review notice'), `${legalDoc.id} prints a review notice`);
    assert.ok(!html.includes('(TM)'), `${legalDoc.id} prints a (TM) mark`);
    assert.ok(!html.includes('legal document library'), `${legalDoc.id} leaks implementation vocabulary`);
    assert.ok(!html.includes('should be reviewed by counsel'), `${legalDoc.id} prints a drafting to-do`);
    assert.ok(!html.includes('Use TM for unregistered marks'), `${legalDoc.id} prints a drafting note`);
    assert.ok(!html.includes('Operational baseline only'), `${legalDoc.id} prints an internal readiness note`);
  }
});

test('printable html header and footer are buyer-facing professional', () => {
  for (const legalDoc of legalDocuments) {
    const html = legalDocumentToHtml(legalDoc);
    assert.ok(html.includes('XBAR LLC™'), `${legalDoc.id} header lacks the proper mark`);
    assert.ok(html.includes('Generated by XBAR LLC.'), `${legalDoc.id} footer wording is wrong`);
  }
});

test('disclaimers keep their verified-good wording', () => {
  const body = legalDocuments.flatMap((doc) => doc.sections.flatMap((s) => s.body)).join(' ');
  assert.ok(body.includes('does not provide legal, veterinary, medical, tax, accounting, insurance, registry'));
  assert.ok(!body.includes('does not intentionally store'));
});
