import assert from 'node:assert/strict';
import test from 'node:test';
import { getCheckoutReadiness, planOutcomes, recommendedTier } from '../src/lib/subscriptionDecision.js';
import { subscriptionPlans } from '../src/lib/subscriptionPlans.js';

test('checkout is unavailable while managed billing is paused', () => { const result = getCheckoutReadiness({ billingEnabled: false, canManageBilling: true, hasManagedIdentity: true, hasPaymentLink: true, checkoutInProgress: false }); assert.equal(result.ready, false); assert.match(result.reason, /paused/); });
test('checkout is unavailable without billing permission', () => { const result = getCheckoutReadiness({ billingEnabled: true, canManageBilling: false, hasManagedIdentity: true, hasPaymentLink: true, checkoutInProgress: false }); assert.equal(result.ready, false); assert.match(result.reason, /workspace owner/); });
test('local workspaces need a payment link before checkout is offered', () => { const result = getCheckoutReadiness({ billingEnabled: true, canManageBilling: true, hasManagedIdentity: false, hasPaymentLink: false, checkoutInProgress: false }); assert.equal(result.ready, false); assert.match(result.reason, /Sign in/); });
test('managed identity or a payment link makes checkout available only when billing is enabled', () => { assert.equal(getCheckoutReadiness({ billingEnabled: true, canManageBilling: true, hasManagedIdentity: true, hasPaymentLink: false, checkoutInProgress: false }).ready, true); assert.equal(getCheckoutReadiness({ billingEnabled: true, canManageBilling: true, hasManagedIdentity: false, hasPaymentLink: true, checkoutInProgress: false }).ready, true); });
test('recommendation moves one operating level at a time and respects selection', () => { assert.equal(recommendedTier('Starter'), 'Professional'); assert.equal(recommendedTier('Enterprise'), 'Enterprise'); assert.equal(recommendedTier('Starter', 'Ranch Ops'), 'Ranch Ops'); assert.match(planOutcomes['Ranch Ops'].join(' '), /one rhythm/); });
test('subscription prices stay aligned to the current approved pricing table', () => { assert.equal(subscriptionPlans.Starter.monthlyRate, 29); assert.equal(subscriptionPlans.Professional.monthlyRate, 79); assert.equal(subscriptionPlans['Ranch Ops'].monthlyRate, 199); assert.equal(subscriptionPlans.Enterprise.monthlyRate, 499); });
