// Sample buyer sale packet for the public /demo page.
//
// This mirrors the print format produced by the application's packet
// generator (src/lib/localSalePacketGenerator.ts) — same sections, same
// watermark treatment, same buyer-verification notice — populated with a
// clearly-labeled FICTIONAL horse so visitors can inspect the real output
// format without any customer data being involved.

const DISCLAIMER =
  'XBAR LLC(TM) generates this packet from user-supplied records. XBAR does not independently verify horse identity, ownership, registration, liens, veterinary condition, health status, sale terms, or transfer validity. Buyers and sellers must independently verify all information before payment, transport, breeding, insurance, or transfer.';

function row(label, value) {
  return `<tr><th>${label}</th><td>${value || '—'}</td></tr>`;
}

export function renderSamplePacket() {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="robots" content="noindex, nofollow">
<title>SAMPLE — XBAR Buyer Sale Packet (fictional horse)</title>
<meta name="description" content="A sample of the watermarked buyer sale packet XBAR generates, using fictional data.">
<style>
@page{margin:0.65in}
body{font-family:Arial,sans-serif;margin:0;color:#15202b;background:#e9edf2;line-height:1.5}
.sample-banner{background:#0b2a4a;color:#fff;text-align:center;padding:10px 16px;font-size:13px}
.sample-banner a{color:#8ec2ff}
.packet{position:relative;max-width:860px;margin:24px auto;background:#fff;box-shadow:0 10px 34px rgba(10,20,35,.18);padding:34px;overflow:hidden}
.watermark{position:absolute;inset:38% auto auto 8%;font-size:78px;letter-spacing:.18em;color:rgba(17,38,66,.055);transform:rotate(-22deg);font-weight:800;z-index:0;pointer-events:none}
.sample-stamp{position:absolute;top:18%;right:-40px;transform:rotate(24deg);font-size:44px;font-weight:800;color:rgba(190,40,40,.16);letter-spacing:.14em;z-index:0}
.content{position:relative;z-index:1}
header{border-bottom:3px solid #17202a;padding-bottom:18px;margin-bottom:22px}
.eyebrow{text-transform:uppercase;letter-spacing:.18em;font-size:11px;color:#315a86;font-weight:700}
h1{font-size:28px;margin:8px 0 4px}
h2{font-size:15px;margin:24px 0 8px;text-transform:uppercase;letter-spacing:.08em;color:#17202a}
.meta{display:flex;gap:12px;flex-wrap:wrap;color:#526273;font-size:12px}
.notice{border:1px solid #d7c37a;background:#fff9e6;padding:12px;margin:14px 0}
.clear{border:1px solid #9fd7b1;background:#effaf3;padding:12px;margin:14px 0}
table{width:100%;border-collapse:collapse;margin-top:8px}
th,td{border:1px solid #d8dee6;padding:8px;text-align:left;vertical-align:top;font-size:12px}
th{width:30%;background:#f4f7fa}
.doc-card{border:1px solid #d8dee6;padding:10px;margin:8px 0}
.doc-card strong{display:block}
.footer{margin-top:26px;border-top:1px solid #d8dee6;padding-top:10px;font-size:11px;color:#64748b}
.signature-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:24px}
.signature-line{border-top:1px solid #17202a;padding-top:8px;font-size:12px}
@media print{body{background:#fff}.packet{box-shadow:none;margin:0;max-width:none}.sample-banner{display:none}}
</style>
</head>
<body>
<div class="sample-banner"><strong>SAMPLE PACKET.</strong> Every name, number, and record below is fictional. This shows the format XBAR generates from your verified records. <a href="/demo">Back to the product tour</a></div>
<div class="packet">
<div class="watermark">XBAR</div>
<div class="sample-stamp">SAMPLE</div>
<div class="content">
<header>
  <div class="eyebrow">XBAR LLC(TM) Buyer Sale Packet — SAMPLE</div>
  <h1>Example Doc Bar (fictional)</h1>
  <div class="meta"><span>Generated as a public sample</span><span>Generated by XBAR demo content</span><span>Packet score 92%</span><span>Cleared for release</span></div>
</header>
<section class="clear"><strong>Cleared for release</strong><p>All required proof documents are approved and the ownership record shows no open transfer. This packet may be shared with the buyer.</p><p><strong>Next action:</strong> Send to buyer and log the release in the audit trail.</p></section>
<section class="notice"><strong>Buyer verification notice:</strong><p>${DISCLAIMER}</p></section>
<section><h2>Horse identity</h2><table>
${row('Registered name', 'Example Doc Bar (fictional)')}
${row('Barn name', 'Doc')}
${row('Breed', 'Quarter Horse')}
${row('Sex', 'Mare')}
${row('Color', 'Sorrel')}
${row('Foaled', '2019-04-02')}
${row('Registry', 'Example registry (fictional)')}
${row('Registration number', 'SAMPLE-0000000')}
${row('Microchip', '(not chipped)')}
</table></section>
<section><h2>Sale and buyer posture</h2><table>
${row('Ask price', '$25,000 (example figure)')}
${row('Listing state', 'Listed')}
${row('Buyer confidence', '92%')}
${row('Watchlist count', '3')}
${row('Inquiry count', '2')}
</table></section>
<section><h2>Ownership and transfer</h2><table>
${row('Legal owner', 'Example Ranch LLC (fictional)')}
${row('Owner entity', 'Example Ranch LLC (fictional)')}
${row('Transfer status', 'Clear')}
${row('Pending documents', 'None')}
${row('Compliance deadline', 'None on record')}
</table></section>
<section><h2>Care and disclosure summary</h2><table>
${row('Horse status', 'Sale Prep')}
${row('Last vet visit', '2026-06-18 (example)')}
${row('Veterinarian', 'Example Equine Clinic (fictional)')}
${row('Farrier', 'Example Farrier Service (fictional)')}
${row('Medical notes', 'Example disclosure: no known conditions recorded. Real packets print the seller’s written disclosures here.')}
</table></section>
<section><h2>Release blockers</h2><p>No hard blockers flagged by XBAR release gate.</p></section>
<section><h2>Warnings</h2><p>No warnings flagged by XBAR release gate.</p></section>
<section><h2>Included proof documents</h2>
<div class="doc-card"><strong>Coggins · Negative EIA test (example)</strong><span>Uploaded 2026-05-30 · Confidence 97%</span><p>Example entry — a real packet lists each approved document with its upload date and review confidence.</p></div>
<div class="doc-card"><strong>Registration · Registry certificate (example)</strong><span>Uploaded 2026-05-12 · Confidence 95%</span><p>Example entry showing how registration proof appears to the buyer.</p></div>
<div class="doc-card"><strong>Bill of Sale · Prior transfer (example)</strong><span>Uploaded 2026-05-12 · Confidence 93%</span><p>Example entry — chain-of-title documents included as buyer-reviewable proof.</p></div>
</section>
<section><h2>Seller review</h2><p>This packet is prepared for buyer review. Seller should confirm all included proof, disclosures, pricing, transfer status, and health records before sending.</p>
<div class="signature-grid"><div class="signature-line">Seller / authorized representative</div><div class="signature-line">Date</div></div></section>
<div class="footer">SAMPLE generated for the public XBAR product tour (/demo) — all data fictional. Generated by XBAR LLC(TM). XBAR(TM), XBAR Listings(TM), and related marks are trademarks or service marks claimed by XBAR LLC. This packet is not legal, veterinary, tax, registry, insurance, escrow, or brokerage advice.</div>
</div>
</div>
</body>
</html>
`;
}
