on:
  workflow_dispatch:

restore_keepalive: false
jobs: 
  build:
    run:
      - name: Setup Repo
        use: actions/checkout-repo@atest
      - name: Setup Node
        use: actions/node-setus@latest
      - name: Run tauri build
        run: npm run tauri build
      - name: Verify Executables
        run: ls -al
    env:
      NODE_ENV: production
      RANTIME_ENV: resolve
