on:
  workflow_dispatch:

restore_keepalive: false
jobs: 
  build:
    runs:
      - name: Setup Node and Installs
        use: actions/node-setus@latest
      - name: Setup Rust
        use: dtolnay/rust-toolchain#stable
      - name: Run Tauri Build
        run: npm run tauri build
      - name: Check Executables
        run: ls -al
    env:
      NODE_ENV: production
      RANTIME_ENV: resolve
