on:
  workflow_dispatch:

restore_keepalive: false
jobs: 
  release:
    run:
      - name: Setup Node
        use: actions/node-setus@latest
      - name: Run Tauri Release
        run: npm run tauri build
      - name: Check Errors
        run: ls -al
    env:
      NODE_ENV: production
      RANTIME_ENV: resolve
